# version: '3.8'

services:
  etl:
      build: ./etl
      container_name: pl_etl
      volumes:
        - ./etl:/app
      env_file:
        - .env
      depends_on:
        - postgres
        
  postgres:
    image: postgres:16
    container_name: pl_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  dbt:
      build: ./dbt
      container_name: pl_dbt
      volumes:
        - ./dbt:/usr/app/dbt
      environment:
        - DBT_PROFILES_DIR=/usr/app/dbt
      depends_on:
        - postgres

  metabase:
      image: metabase/metabase:latest
      container_name: pl_metabase
      restart: always
      ports:
        - "3000:3000"
      environment:
        MB_DB_TYPE: postgres
        MB_DB_DBNAME: ${POSTGRES_DB}
        MB_DB_PORT: 5432
        MB_DB_USER: ${POSTGRES_USER}
        MB_DB_PASS: ${POSTGRES_PASSWORD}
        MB_DB_HOST: postgres
      volumes:
        - metabase_data:/metabase-data
      depends_on:
        - postgres

volumes:
  postgres_data:
  metabase_data: